# Generated by Django 6.0.2 on 2026-02-17 03:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True)),
                ('height', models.FloatField(help_text='Height in cm', null=True)),
                ('weight', models.FloatField(help_text='Weight in kg', null=True)),
                ('lifestyle_data', models.JSONField(blank=True, default=dict, help_text='Smoking, Alcohol, Exercise')),
                ('family_history', models.JSONField(blank=True, default=list, help_text='List of conditions')),
                ('conditions', models.JSONField(blank=True, default=list, help_text='Existing conditions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
