# Generated by Django 6.0.2 on 2026-02-17 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Screening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Pending_Analysis', 'Pending Analysis'), ('Completed', 'Completed')], default='Draft', max_length=20)),
                ('vitals', models.JSONField(blank=True, default=dict, help_text='BP, Heart Rate, etc.')),
                ('symptoms', models.JSONField(blank=True, default=list, help_text='List of symptoms')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_screenings', to='accounts.doctorprofile')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenings', to='patients.patientprofile')),
            ],
        ),
    ]
