# Generated by Django 6.0.2 on 2026-02-17 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('screenings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metabolic_score', models.IntegerField(default=0)),
                ('diabetes_risk_1yr', models.FloatField(null=True)),
                ('diabetes_risk_5yr', models.FloatField(null=True)),
                ('heart_risk', models.FloatField(null=True)),
                ('fatty_liver_risk', models.FloatField(null=True)),
                ('obesity_risk', models.FloatField(null=True)),
                ('insulin_resistance_score', models.FloatField(null=True)),
                ('syndrome_flags', models.JSONField(blank=True, default=list, help_text='Metabolic Syndrome criteria met')),
                ('abnormal_markers', models.JSONField(blank=True, default=list, help_text='Biomarkers out of range')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('screening', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_result', to='screenings.screening')),
            ],
        ),
    ]
