# Generated by Django 6.0.2 on 2026-02-17 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('screenings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiomarkerPanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('glucose_fasting', models.FloatField(blank=True, null=True)),
                ('glucose_pp', models.FloatField(blank=True, null=True)),
                ('hba1c', models.FloatField(blank=True, null=True)),
                ('hdl', models.FloatField(blank=True, null=True)),
                ('ldl', models.FloatField(blank=True, null=True)),
                ('triglycerides', models.FloatField(blank=True, null=True)),
                ('cholesterol', models.FloatField(blank=True, help_text='Total Cholesterol', null=True)),
                ('creatinine', models.FloatField(blank=True, null=True)),
                ('urea', models.FloatField(blank=True, null=True)),
                ('alt', models.FloatField(blank=True, null=True)),
                ('ast', models.FloatField(blank=True, null=True)),
                ('insulin', models.FloatField(blank=True, null=True)),
                ('tsh', models.FloatField(blank=True, null=True)),
                ('crp', models.FloatField(blank=True, null=True)),
                ('esr', models.FloatField(blank=True, null=True)),
                ('screening', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='biomarker_panel', to='screenings.screening')),
            ],
        ),
    ]
